# Generated by Django 3.1.7 on 2021-04-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='disc',
            new_name='desc',
        ),
    ]
